### ISSUE TITLE
`zenodraft` fails upon upload of files using the zenodo.org with `UNSUPPORTED MEDIA TYPE` error

### ISSUE THREAD

**Issue by alexlancaster** [zenodraft/action#25]
With the release of the new zenodo backend, the action can still create the initial deposition, however if fails on upload of files.  I can see the initial upload as a draft on zenodo.org, but it doesn't complete the upload, so the draft deposition isn't finalized:

Here's an example of a failed github action using the primary main zenodo.org instance (not the 'sandbox') upload:

```
  adding file pypop.zip to deposition with id 10004060...
  Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: {
      body: PassThrough {
        _readableState: [ReadableState],
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        _writableState: [WritableState],
        allowHalfOpen: true,
        [Symbol(kCapture)]: false,
        [Symbol(kCallback)]: null
      },
      disturbed: false,
      error: null
    },
    [Symbol(Response internals)]: {
      url: 'https://zenodo.org/api/files/9aa30b17-8a3a-485a-befc-5660c096f6f8/pypop.zip',
      status: 415,
      statusText: 'UNSUPPORTED MEDIA TYPE',
      headers: Headers { [Symbol(map)]: [Object: null prototype] },
      counter: 0
    }
  }
  Error: Something went wrong on PUT to https://zenodo.org/api/files/9aa30b17-8a3a-485a-befc-5660c096f6f8/pypop.zip: 415 - UNSUPPORTED MEDIA TYPE 
```

full log is here:

https://github.com/alexlancaster/pypop/actions/runs/6521588081/job/17710317405#step:6:484

It's not clear if this is a temporary issue with file uploads, or something more structural that the `zenodraft` action needs to adjust.  I also tried with `.tar.gz` as an option and had the same problem.    I do note that I can visit the partially-deposited record and manually upload the same .zip or .tar.gz file and it works.  So it makes me think that the API has changed slightly.

**Comment by alexlancaster** [comment]
I even went back and deleted the old token and recreated them, with the deposit:write and deposit:actions both enabled.  Same problem.

**Comment by alexlancaster** [comment]
@jspaaks I did a fork of zenodraft: https://github.com/alexlancaster/zenodraft and tested the cli version with setting the content headers to `application/octet-stream` and it works:

```
npx zenodraft file add 10002385 pypop-genomics-0.9.24.tar.gz 
```

runs to completion.  And I can query the record to see the uploaded file here:

```
npx zenodraft deposition show details 10002385
{
    "created": "2023-10-14T02:51:57.851606+00:00",
    "modified": "2023-10-16T22:48:02.463366+00:00",
    "id": 10002385,
    "conceptrecid": "10002384",
    "doi": "10.5281/zenodo.10002385",
    "doi_url": "https://doi.org/10.5281/zenodo.10002385",
    "metadata": {
        "title": "PyPop draft (not for publishing)",
        "doi": "10.5281/zenodo.10002385",
        "publication_date": "2023",
        "access_right": "open",
        "creators": [
            {
                "name": "Lancaster, Alexander",
                "affiliation": "Ronin Institute",
                "orcid": "0000-0002-0002-9263"
            }
        ],
        "version": "v0.9.105",
        "grants": [
            {
                "id": "10.13039/100000002::5U24AI049213-02"
            },
            {
                "id": "0155zta11::2014"
            },
            {
                "id": "01643wd06::foo"
            }
        ],
        "imprint_publisher": "Zenodo",
        "upload_type": "software",
        "prereserve_doi": {
            "doi": "10.5281/zenodo.10002385",
            "recid": 10002385
        }
    },
    "title": "PyPop draft (not for publishing)",
    "links": {
        "self": "https://zenodo.org/api/deposit/depositions/10002385",
        "html": "https://zenodo.org/deposit/10002385",
        "doi": "https://doi.org/10.5281/zenodo.10002385",
        "badge": "https://zenodo.org/badge/doi/10.5281%2Fzenodo.10002385.svg",
        "files": "https://zenodo.org/api/deposit/depositions/10002385/files",
        "bucket": "https://zenodo.org/api/files/e589dbf8-3d4e-4985-8979-e3681e7cc9d1",
        "latest_draft": "https://zenodo.org/api/deposit/depositions/10002385",
        "latest_draft_html": "https://zenodo.org/deposit/10002385",
        "publish": "https://zenodo.org/api/deposit/depositions/10002385/actions/publish",
        "edit": "https://zenodo.org/api/deposit/depositions/10002385/actions/edit",
        "discard": "https://zenodo.org/api/deposit/depositions/10002385/actions/discard",
        "newversion": "https://zenodo.org/api/deposit/depositions/10002385/actions/newversion",
        "registerconceptdoi": "https://zenodo.org/api/deposit/depositions/10002385/actions/registerconceptdoi"
    },
    "record_id": 10002385,
    "owner": 401706,
    "files": [
        {
            "id": "2ea63b23-c734-4534-8d98-6a9ee5f0025d",
            "filename": "build_wheels.yml",
            "filesize": 10056,
            "checksum": "8b231accdf0eea41244975e72170c160",
            "links": {
                "self": "https://zenodo.org/api/deposit/depositions/10002385/files/2ea63b23-c734-4534-8d98-6a9ee5f0025d",
                "download": "https://zenodo.org/api/files/e589dbf8-3d4e-4985-8979-e3681e7cc9d1/build_wheels.yml"
            }
        },
        {
            "id": "3850e829-8ffc-4df0-9ca9-d13203f018cb",
            "filename": "test-output.tar.gz",
            "filesize": 39572,
            "checksum": "5a81080be025f80e8e5508db6538dd27",
            "links": {
                "self": "https://zenodo.org/api/deposit/depositions/10002385/files/3850e829-8ffc-4df0-9ca9-d13203f018cb",
                "download": "https://zenodo.org/api/files/e589dbf8-3d4e-4985-8979-e3681e7cc9d1/test-output.tar.gz"
            }
        },
        {
            "id": "c5278204-5311-4f29-af92-a39ebeec0410",
            "filename": "arm64-artifact.zip",
            "filesize": 8076246,
            "checksum": "f0f4c60b931454b7ceb08b11ebe973d9",
            "links": {
                "self": "https://zenodo.org/api/deposit/depositions/10002385/files/c5278204-5311-4f29-af92-a39ebeec0410",
                "download": "https://zenodo.org/api/files/e589dbf8-3d4e-4985-8979-e3681e7cc9d1/arm64-artifact.zip"
            }
        },
        {
            "id": "1f099573-d0e7-4cdf-863e-bba940f3b77c",
            **"filename": "pypop-genomics-0.9.24.tar.gz",**
            "filesize": 6996454,
            "checksum": "83f5508b693a8d4b2af58e9afbb5976e",
            "links": {
                "self": "https://zenodo.org/api/deposit/depositions/10002385/files/1f099573-d0e7-4cdf-863e-bba940f3b77c",
                "download": "https://zenodo.org/api/files/e589dbf8-3d4e-4985-8979-e3681e7cc9d1/pypop-genomics-0.9.24.tar.gz"
            }
        }
    ],
    "state": "unsubmitted",
    "submitted": false
}
```

**Comment by jspaaks** [comment]
Thanks, good to know. I'm quite busy at the moment with some other commitments, but that's not a big deal -- I would've waited until Zenodo's new setup stabilizes anyway

**Comment by alexlancaster** [comment]
> Thanks, good to know. I'm quite busy at the moment with some other commitments, but that's not a big deal -- I would've waited until Zenodo's new setup stabilizes anyway

@jspaaks Unfortunately it's broken again for a different reason (FORBIDDEN error), see the comment on the PR: https://github.com/zenodraft/zenodraft/pull/78#issuecomment-1773116442

I've reported it upstream again.

**Comment by alexlancaster** [comment]
> > Thanks, good to know. I'm quite busy at the moment with some other commitments, but that's not a big deal -- I would've waited until Zenodo's new setup stabilizes anyway
> 
> @jspaaks Unfortunately it's broken again for a different reason (FORBIDDEN error), see the comment on the PR: [zenodraft/zenodraft#78 (comment)](https://github.com/zenodraft/zenodraft/pull/78#issuecomment-1773116442)
> 
> I've reported it upstream again.

It's odd.  There was a window where I was briefly able to upload via the `zenodraft` command line:

```
npx zenodraft -v file add 10027957 pypop-genomics-0.0.post1+g630a10a.tar.gz 
adding file pypop-genomics-0.0.post1+g630a10a.tar.gz to deposition with id 10027957...
```

didn't return any `403` errors.  But now it's doing it again. Metadata uploads are fine.  Something is unstable

**Comment by alexlancaster** [comment]
@jspaaks good news is that the API seems to be a lot more stable now.  I've been communicating with the zenodo developers on debugging the failures, and apparently have found the source of the flakiness as a concurrency, and mostly fixed with this: https://github.com/zenodo/zenodo-rdm/commit/652287e6bb783934dcda64762158250cc90a595b

I haven't (yet) tried whether backing out my changes and reverting to the old API using the specific MIME types works again (which would make this PR unnecessary), but I think that is supposed to be change going forward.

**Comment by alexlancaster** [comment]
@jspaaks see my update on PR  https://github.com/zenodraft/zenodraft/pull/78  - the "new version" API seems to have changed

**Comment by alexlancaster** [comment]
With the PR in https://github.com/zenodraft/zenodraft/pull/79 now merged, it looks like this action is working out of the box with the new API.  See with pypop, for example: https://github.com/alexlancaster/pypop/actions/runs/7795044827

Closing this issue.
